export enum Prompts {
    FUNDAMENTALS = "fundamentals",
    ROUTES = "routes",
    RENDERING = "rendering",
    COMPONENTS = "components",
    DATA_FETCHING = "data_fetching",
    API_ROUTES = "api_routes",
    NAVIGATION = "navigation",
    STYLING = "styling",
    STATES = "states",
    AUTHENTICATION = "authentication",
    PERFORMANCE = "performance",
    DEPLOYMENT = "deployment",
    DATABASE_INTEGRATION = "database_integration",
    MIDDLEWARE = "middleware",
    SEO = "seo",
    INTERNATIONALIZATION = "internationalization",
    BEST_PRACTICES = "best_practices",
}